name: bus_yaracuy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0-beta.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bg.jpg
    - lib/assets/data/mantenimientos.json
